# Change these first
owner: IC-Naming # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  # - name: ICP-Favorites
  #   url: https://crp26-tyaaa-aaaam-aacbq-cai.raw.ic0.app/metrics
  # - name: ICP-Registrar
  #   url: https://cymrc-fqaaa-aaaam-aacaa-cai.raw.ic0.app/metrics
  # - name: ICP-Resolver
  #   url: https://cwo4k-6aaaa-aaaam-aacba-cai.raw.ic0.app/metrics
  # - name: ICP-Registry
  #   url: https://c7nxw-iiaaa-aaaam-aacaq-cai.raw.ic0.app/metrics
  # - name: ICP-ICNaming-Ledger
  #   url: https://ceilt-sqaaa-aaaam-aacca-cai.raw.ic0.app/metrics
  # - name: ICP-Registrar-Control_Gateway
  #   url: https://gjzpj-bqaaa-aaaam-aacya-cai.raw.ic0.app/metrics
  - name: ICNaming-WWW
    url: http://www.icnaming.com/
  - name: ICNaming-APP
    url: http://app.icnaming.com/
  # - name: ICNaming-Preprod
  #   url: http://preprod.icnaming.com/
  # - name: TICP-Favorites
  #   url: https://oyjuw-oqaaa-aaaal-qac5q-cai.raw.ic0.app/metrics
  # - name: TICP-Registrar
  #   url: https://onof3-pyaaa-aaaal-qac6a-cai.raw.ic0.app/metrics
  # - name: TICP-Resolver
  #   url: https://okpdp-caaaa-aaaal-qac6q-cai.raw.ic0.app/metrics
  # - name: TICP-Registry
  #   url: https://cxnwn-diaaa-aaaag-aabaq-cai.raw.ic0.app/metrics
  # - name: TICP-ICNaming-Ledger
  #   url: https://ra2t7-3aaaa-aaaaj-aahzq-cai.raw.ic0.app/metrics
  # - name: TICP-Registrar-Control_Gateway
  #   url: https://j6dzz-gaaaa-aaaak-aab3q-cai.raw.ic0.app/metrics
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.icnaming.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/icnaming/uptime/main/assets/logo192.png
  name: ICNaming
  introTitle: "**ICNaming** Decentralized Name Service on IC"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://app.icnaming.com
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Status Repo
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
